# Generated by Django 3.1.5 on 2021-02-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(choices=[(1, 'Admin'), (2, 'Mechenic'), (3, 'Customer')], default=3, max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('conf_password', models.CharField(max_length=20)),
            ],
        ),
    ]
