# Generated by Django 3.0.5 on 2021-02-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
