# Generated by Django 3.0.5 on 2021-02-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0002_cus_request_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cus_request',
            name='payment_status',
            field=models.BooleanField(default=0),
        ),
    ]
