# Generated by Django 3.0.5 on 2021-02-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0003_auto_20210219_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cus_request',
            name='payment_status',
            field=models.BooleanField(default=True),
        ),
    ]
