# Generated by Django 3.1.5 on 2021-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0003_auto_20210201_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('salary', models.FloatField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Mechenic', 'Mechenic'), ('Customer', 'Customer')], default='Customer', max_length=10)),
            ],
        ),
    ]
