# Generated by Django 3.0.5 on 2021-02-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0004_auto_20210219_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50, null=True)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='job_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('post_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cus_request',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
