# Generated by Django 3.1.5 on 2021-02-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0006_cus_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cus_request',
            name='category',
            field=models.CharField(max_length=40),
        ),
    ]
