# Generated by Django 3.0.5 on 2021-02-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0008_auto_20210206_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='fname',
        ),
    ]
