# Generated by Django 3.0.5 on 2021-02-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0010_auto_20210206_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='username',
        ),
    ]
