# Generated by Django 3.0.5 on 2021-02-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0011_auto_20210206_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=30)),
                ('msg', models.CharField(max_length=200)),
            ],
        ),
    ]
