# Generated by Django 3.0.5 on 2021-02-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0012_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
