# Generated by Django 3.0.5 on 2021-02-10 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0013_auto_20210209_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=40, null=True)),
                ('Mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CCC.mechanic')),
            ],
        ),
    ]
