# Generated by Django 3.0.5 on 2021-02-10 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0014_apply_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_leave',
            name='admin_reason',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
