# Generated by Django 3.0.5 on 2021-02-11 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0015_apply_leave_admin_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 2, 11, 7, 31, 20, 191469, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
